### ISSUE TITLE
Adding mobile wallet-friendly wording

### ISSUE THREAD

**Issue by p0s** [antonnell/networklist-org#1]
We will use https://chainlist.org/ in our https://token.im/ mobile wallet's dapp browser. Users will be able to use it (as one option) to switch between networks.

Now, when I open chainlist.org in my imToken dapp browser it shows the Metamask logo and says 'Add to Metamask'.

For easier understanding, I'd like to have the site detect the dapp browser (i.e. in this case imtoken) and show imToken logo as well as 'Add to imToken' in the relevant case.

Detecting via https://docs.token.im/dapp-sdk/en/#detect-imtoken (is also possible for other mobile wallets)

**Comment by p0s** [comment]
@andrecronje can we add this feature? we'd add the PR ourselves. just want to ask upfront.

**Comment by antonnell** [comment]
Hey @p0s 

Yes you can make that change. I like it!

**Comment by p0s** [comment]
Closing as it's solved in #2
