### ISSUE TITLE
[Suggestion] Deep linking

### ISSUE THREAD

**Issue by DavidBurela** [antonnell/networklist-org#14]
# Suggestion
Enable deep linking, e.g. `https://chainlist.org/?chain=xdai`

Result of deep linking could be:
 - Navigate direct to a single entry.
 - Populating the search field

Populating the search field may be the lowest technical hurdle, as there is no new UI.  Just a function to parse querystring -> populate searchfield textbox

## Why?
So that it can be used in documentation to assist onboard users.

I was going through the steps to use Metamask with xDai, and they helpfully link to chainlist frontpage.  Allowing a deep link straight to the details of that entry could help with UX on chainlist

Document page for reference https://www.xdaichain.com/for-users/wallets/metamask/metamask-setup#setting-up-metamask-for-xdai

**Comment by antonnell** [comment]
PR #16 
Went with "Populate the search field" route. https://chainlist.org/?search=xdai
Deployed in version 1.0.5
