### ISSUE TITLE
Change rpc for polygon

### ISSUE THREAD

**Issue by Ratio2** [antonnell/networklist-org#24]
In https://chainid.network/chains.json we have old sometime buggy rpc urls

According to official doc https://docs.matic.network/docs/develop/network-details/network/
New unified URL (recommended): https://polygon-rpc.com/
Use this new aggregated RPC link to avoid RPC disconnects.

**Comment by ti0** [comment]
This is not the official network suggested by the MATIC docs, while the one listed on chainlist is outdated and buggy, the matic network lists:

- https://rpc-mainnet.maticvigil.com/ for Mainnet
- https://rpc-mumbai.maticvigil.com/ for Testnet

As listed on https://docs.matic.network/docs/develop/metamask/config-polygon-on-metamask/

**Comment by imsys** [comment]
Two official documents saying different things. I'm using the same @Ratio2 mentioned, but maybe we will have to get a Polygon dev to clear this up.

**Comment by yanis7774** [comment]
Same for Fantom Network. 
You use: https://rpcapi.fantom.network - too buggy. I literally spent two days debugging my Dapp, but it was just the wrong RPC URL.
Oficial Docs [says](https://docs.fantom.foundation/api/public-api-endpoints): https://rpc.ftm.tools - so after I've changed it, everything goes well.

**Comment by antonnell** [comment]
You can submit all changes to the ethereum-lists repo https://github.com/ethereum-lists/chains
I pull data from there and display it. 
Note, I only use the first RPC url that is returned in the array.

FTM has been changed for a couple of weeks now.
