### ISSUE TITLE
Style breaking under mobile

### ISSUE THREAD

**Issue by 0xashu** [antonnell/networklist-org#8]
Hey @antonnell 
Style issues will occur if chainlist.org is accessed with a mobile or wallet browser, but not when debugging responsive with Chrome.

Maybe it's related to this [commit](https://github.com/antonnell/networklist-org/commit/38471a6f63834bb8cb089e469355ed759a5a99ea)

![Image from iOS](https://user-images.githubusercontent.com/3678166/113275072-f5f27700-9310-11eb-9ef9-e2cf574fd52b.png)

**Comment by 0xashu** [comment]
@antonnell 
Have you deployed it yet?
There are still issues with the style at the moment

**Comment by p0s** [comment]
@antonnell could you deploy a version with this?
